### ISSUE TITLE
get_content() gives different results from v1/content endpoint

### ISSUE THREAD

**Issue by kmasiello** [rstudio/connectapi#114]
Testing on Colorado, the script below yields a 3983 x 28 df using the API endpoint, and 3761 x 36 df using get_content().

```
library(httr)
library(tidyr)
# Use the /v1/content endpoint to retrieve the full list of content items
result <- GET(
  paste0(Sys.getenv("CONNECT_SERVER"),"__api__/v1/content"),
    add_headers(Authorization = paste("Key", Sys.getenv("CONNECT_API_KEY"))))
# Create a tibble for the content list result response
content_list <- unnest_wider(tibble::tibble(dat = content(result)), dat)
# Use connectapi 
content_list2 <- get_content(client, limit = Inf)
```

**Comment by colearendt** [comment]
Traced this down - the difference is that the new `v1/content` endpoint returns "Unpublished" content.

**Comment by kmasiello** [comment]
Also hoping`connectapi` will return character output for app_mode consistent with the endpoint rather than numeric:

from `connectapi` https://github.com/rstudio/connectapi/blob/002f0a6a0a6d3cf2eadc57f3daf173dd13ca65ff/R/ptype.R#L56
#(1=shiny, 2=shiny Rmd, 3=source Rmd, 4=static, 5=api, 6=tensorflow, 7=python, 8=flask, 9=dash, 10=streamlit)

Endpoint description
api - R code defining a Plumber API.
jupyter-static - A Jupyter Notebook.
python-api - Python code defining an API (such as Flask)
python-bokeh - Python code defining a Bokeh application.
python-dash - Python code defining a Dash application.
python-streamlit - Python code defining a Streamlit application.
rmd-shiny - An R Markdown document with a Shiny runtime.
rmd-static - An R Markdown document or site.
shiny - R code defining a Shiny application.
static - Content deployed without source; often HTML and plots.
tensorflow-saved-model - A TensorFlow Model API.
unknown - No known runtime model.
