### ISSUE TITLE
Ideas for new development

### ISSUE THREAD

**Issue by mac-pfa** [rstudio/connectapi#12]
Hi guys, thanks for the work you are putting in!
I hope it's okay to suggest some ideas for new development.
We would like to use this package as core functionality in our deploy chain setup, so it would mean a lot.

Our ideas for new functionality:
- setting who can view the app
- adding collaborators
- setting the run-as user
- setting the runtime settings
- setting the schedule settings
- setting the tags
- update the promote function so it is not necessary to download and re-deploy a bundle manually - and allow us to supply the arguments above along with new name, title, image, and vanity url

Also, could you add a function to retrieve a tibble of the currently deployed apps?
For now, we retrieve them with an ugly nested lapply
```
apps_tbl <- lapply(X   = client$get_apps(),
                   FUN = function(x) {

                     lapply(X   = x,
                            FUN = function(y) {

                              ifelse(test = y %>% is.null(),
                                     yes  = NA,
                                     no   = y)

                            }
                     ) %>%
                       as_tibble()
                   }
) %>%
  bind_rows()
```

Thanks! :)

**Comment by colearendt** [comment]
Thanks for the thoughts and feedback! A question on the promotion process - have you explored the new README? What are your thoughts on this workflow for promotion? We felt like the `promote` function started feeling weird with all the "from" and "to" arguments and that breaking things into the appropriate pieces might be a bit more clear.

```r
library(connectapi)

client <- connect(
  host = "dev.example.com",
  api_key = "my-dev-key"
)

client_prod <- connect(
  host = "prod.example.com",
  api_key = "my-secret-key"
)

# get bundle
to_prod_bnd <- client %>%
  content_item("the-guid-to-promote") %>%
  download_bundle()

# promote to production
prod_content <- client_prod %>%
  deploy(to_prod_bnd, title = "Now in Production") %>%
  set_vanity_url("/my-app") %>%
  set_image_path("/path/to/my.png") 

prod_content %>%
  poll_task()
```

**Comment by mac-pfa** [comment]
Yes, but we have just created our own promote function as a wrapper around the new promote workflow from the README, and then we use a config file in order to reduce the many arguments.

**Comment by colearendt** [comment]
Ahh interesting! Good to know, thanks!

**Comment by colearendt** [comment]
All of these should be available now! Please let us know if you run into any issues! Some of the documentation is a little lacking, but the `pkgdown` site has _some_ details at least: https://rstudio.github.io/connectapi/
