### ISSUE TITLE
fs_dir error

### ISSUE THREAD

**Issue by GShotwell** [rstudio/connectapi#121]
I'm getting an error when trying to bundle a subdirectory which originates from the `fs` package:

```
  rsconnect::writeManifest("docs",
                           appFiles = list.files("docs", recursive = TRUE))
[ENOENT] Failed to search directory 'docs': no such file or directory 
```
The source of this error is this [setwd() code](https://github.com/rstudio/connectapi/blob/b39c14de7029b6bb1dc9c61bb7aaca0782da0a83/R/deploy.R#L119-L121) which I think is unnecessary, is there any reason to do the working directory dance rather than passing path directly to check bundle contents?

**Comment by colearendt** [comment]
Thanks for the report @GShotwell ! I will take a look! Wondering if this is related at all to #118 . 

What function are you using from `connectapi` in this case?

**Comment by GShotwell** [comment]
Oh sorry this error is coming from `connectapi::bundle_dir` basically when you use that on a sub directory it sets the wd to that directory which screws up a `fs` call.
