### ISSUE TITLE
adding environment variables to bundle

### ISSUE THREAD

**Issue by ataustin** [rstudio/connectapi#123]
Hi folks,
Thanks for all your work on `connectapi`!

I've been using the package to bundle directories and publish the contents.  I was wondering whether it is possible to add environment variables directly to the bundle so that they are set upon deployment?  This would be in contrast to the current workflow of deploying a bundle, then getting the environment and setting new variables in that environment.

If it is not currently possible, would you consider adding this feature, or something similar (e.g. passing a list of env variable key-value pairs to and argument in the `deploy` function)?

Thanks for your consideration!

**Comment by colearendt** [comment]
Howdy @ataustin ! So glad to hear this has been helpful for you!

We could definitely make this easier (and document it better). We have added a more flexible argument to the `deploy()` function particularly for this scenario! (or others that are similar). For instance:

```
  deployed <- deploy(
    test_conn_1, bnd, uuid::UUIDgenerate(), 
    .pre_deploy = {
       content %>% get_environment() %>% set_environment_new(VAR1="hi")
  })
```

Will that work for you in the short term? We are definitely hoping to make this better long term (a way to include in the bundle, etc.). However, there are a lot of tricky problems with publishing inside of the bundle.

It is also worth noting that in an upcoming release of Connect, we are planning to include temporary versions of the CONNECT_SERVER and CONNECT_API_KEY env vars automatically in content on RStudio Connect. If that would help with your use case at all, stay tuned to our blog for the release announcement! 😄

**Comment by ataustin** [comment]
Hi Cole, thanks for your response!  The upcoming release of Connect does sound very promising, I'll keep an eye out.

Your short-term solution of using `.pre_deploy` appears to do exactly what I need.  Thanks so much!
