### ISSUE TITLE
get_apps and content_list are missing a single content item

### ISSUE THREAD

**Issue by alessap** [rstudio/connectapi#134]
When retrieving the applications a user can see with `client$get_apps()` one obtains **N-1** applications from RStudio Connect whilst using the RStudio Connect API directly with e.g. `httr` using the endpoint `<SERVER_URL_HERE>/__api__/v1/content` returns **N** applications. This bug takes place at random and my guess is that might be caused by the application list order at the time you retrieve the apps with `connectapi`. The same occurs if one uses `content_list`.

**Comment by colearendt** [comment]
Interesting! Is it possible that you are returning unpublished content? It is surprising that there would only be 1 such item, which suggests this is not your problem, but the `v1/content` API returns Unpublished content by default, which is a change in behavior for the API 

https://github.com/rstudio/connectapi/issues/114

**Comment by toph-allen** [comment]
Closing this, as we haven't heard any more in the past two years, and have not heard any more reports of this bug.
