### ISSUE TITLE
Trying to create users but search is returning two users similar names

### ISSUE THREAD

**Issue by sclewis23** [rstudio/connectapi#135]
I'm using users_create_remote, but I noticed a failure when it says it finds two users.
I'm using AD, and searching based on sAMAccountName, so I thought it would return only one.
Names are very similar: 
Name        sAMAccountName
Hui Li         hui1.li
Hui Liu       hui1.liu

Any why to only select exact match ?
connectapi::users_create_remote(connect = client, prefix = "hui1.li", expect = 1, check = T)

notice the error faults too:
Found 2 remote users. Expected 1
Error in glue_data(.x = NULL, ..., .sep = .sep, .envir = .envir, .open = .open,  : 
  Expecting '}'

Thanks

**Comment by colearendt** [comment]
Sorry for the trouble! I'll take a look at this! Did setting `expect = 2` or `check = FALSE` workaround the issue?

**Comment by sclewis23** [comment]
Hey sorry...code doesn't allow it :
`
  if (check && expect > 1) {
    stop(glue::glue("expect > 1 is not tested. Please set expect = 1, and specify a more narrow 'prefix'. You provided: expect={expect}"))
  }
`
