### ISSUE TITLE
Getting tags from connect api is difficult

### ISSUE THREAD

**Issue by ankitsoni16** [rstudio/connectapi#136]
When trying to get the tags, the column heading is keep interchanging, from app_tags to V2.
How can I get this fixed?

**Comment by colearendt** [comment]
Would you mind sharing a reproducible example so that we can dig into this more directly?

**Comment by colearendt** [comment]
Worth noting that `get_content()` now returns a `tags` column (in latest version that I just pushed). But still much to do in making this better

**Comment by colearendt** [comment]
Just landed usage of the new (1.8.6 and newer, so not _that_ new) RStudio Connect APIs. I believe this will resolve most of your issues. See `get_tag_data()`, and `get_tags()`, along with related functions. 

https://pkgs.rstudio.com/connectapi/reference/tags.html

Hopefully this resolves your issue! Please reopen or open a new issue if not!
