### ISSUE TITLE
Fix random docs / pkgdown things

### ISSUE THREAD

**Issue by colearendt** [rstudio/connectapi#140]
- [x] NEWS.md has an entry that is missing its "function" definition
- [x] NEWS.md links seem to be wrong...? Not using the doc name reference? https://pkgs.rstudio.com/connectapi/news/index.html
- [ ] improve examples?
- [ ] update `CONTRIBUTING.md`
- [ ] add an overview page that defines the general structure
    - R6 object
    - helpers
    - tag mechanism (old vs. new)
    - deployment mechanism
    - ACL mechanism
    - get_ helpers and paging
    - `browse_` helpers
    - schedule stuff
    - audit_ stuff
- [ ] set up better reference groups in pkgdown
- [ ] see if package docs can point to pagedown
- [ ] deprecate acl stuff (not experimental)
- [ ] can sections have descriptions associated with them?
- [ ] finish off the couple of missing tag functions

**Comment by toph-allen** [comment]
Closing as part of issue cleanup. Documentation is being improved, slowly.
