### ISSUE TITLE
Not able to deploy shinyapp to RStudio Connect with connectapi_0.1.0.9033 

### ISSUE THREAD

**Issue by ankitsoni16** [rstudio/connectapi#148]
I am not able to deploy my shiny dashboard at RStudio connect after updating connectapi.

The error which I am getting is :

[Connect] 2022/03/24 04:10:55.084699012 Installing connectapi (0.1.0.9033) ... 
GET /__api__/tasks/Yu6S7AvoX55UoBJA?first_status=368 15ms
[Connect] 2022/03/24 04:10:56.338071839 FAILED
[Connect] 2022/03/24 04:10:56.339128018 Error in getSourceForPkgRecord(pkgRecord, srcDir(project), availablePackagesSource(repos = repos), : Failed to download package from URL:
[Connect] 2022/03/24 04:10:56.339148054 - 'https://api.github.com/repos/rstudio/connectapi/tarball/9ca84e01f04f42962dcf65b23e211eeecfab40eb'
[Connect] 2022/03/24 04:10:56.339177061 
[Connect] 2022/03/24 04:10:56.339182902 Unable to fully restore the R packages associated with this deployment.
[Connect] 2022/03/24 04:10:56.339194653 Please review the preceding messages to determine which package
[Connect] 2022/03/24 04:10:56.339195747 encountered installation difficulty and the cause of the failure.
[Connect] Build error: exit status 1
GET /__api__/applications/512/config 20ms
----- Deployment log finished at  2022-03-24 12:10:56  -----
Warning messages:
1: invalid uid value replaced by that for user 'nobody' 
2: invalid gid value replaced by that for user 'nobody'

**Comment by colearendt** [comment]
Interesting! This looks like an issue with your Connect host - is your RStudio Connect host able to install packages from GitHub?? This URL works fine for me. It may be that you need to install packages another way (i.e. through RStudio Package Manager, etc.). We really want to get `connectapi` on CRAN (#92), which should hopefully simplify your issues here - apologies for the delay on that!

```
curl -IL https://api.github.com/repos/rstudio/connectapi/tarball/9ca84e01f04f42962dcf65b23e211eeecfab40eb
HTTP/2 302
server: GitHub.com
date: Wed, 20 Apr 2022 08:07:49 GMT
content-type: text/html;charset=utf-8
content-length: 0
cache-control: public, must-revalidate, max-age=0
expires: Wed, 20 Apr 2022 08:07:49 GMT
location: https://codeload.github.com/rstudio/connectapi/legacy.tar.gz/9ca84e01f04f42962dcf65b23e211eeecfab40eb
x-ratelimit-limit: 60
x-ratelimit-remaining: 60
x-ratelimit-reset: 1650445669
x-ratelimit-used: 0
x-ratelimit-resource: core
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
vary: Accept-Encoding, Accept, X-Requested-With
x-github-request-id: FF76:5344:78CC4F:14B918A:625FBF5A

HTTP/2 200
access-control-allow-origin: https://render.githubusercontent.com
content-disposition: attachment; filename=rstudio-connectapi-v0.1.0.9033-0-g9ca84e0.tar.gz
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
content-type: application/x-gzip
etag: "ba5032e31074321a70d0b00e989c636629e8d1034af886a686a42c734436d8e4"
strict-transport-security: max-age=31536000
vary: Authorization,Accept-Encoding,Origin
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
date: Wed, 20 Apr 2022 08:07:54 GMT
x-github-request-id: FF77:6456:51617:BE57E:625FBF5A
```

**Comment by colearendt** [comment]
`connectapi` is now on CRAN! Please let us know if you run into any other troubles 😄
