### ISSUE TITLE
Add warning about empty (or null) API key

### ISSUE THREAD

**Issue by colearendt** [rstudio/connectapi#16]
Not sure whether this should be a warning or fatal error, but if your API key is empty or NULL, we currently instantiate a client which behaves a bit strangely because it does not have an API key attached.

**Comment by JosiahParry** [comment]
I personally think this should lead to a fatal error. Otherwise the functions / methods might fail silently and the use may get confused. 

For reference: https://cran.r-project.org/web/packages/httr/vignettes/api-packages.html#authentication
