### ISSUE TITLE
Overlapping methods in connectapi break dbplyr functionality

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/connectapi#177]
Something unexpected is happening with connectapi's custom `tbl_lazy` methods for `op_vars`, `dim` and `dimnames` generics (some of which are probably not necessary with the latest version of dbplyr).

I have some code that relies on `colnames()`, where it's expected that `colnames()` returns the column names of the final table (if we take out `x`, then it shouldn't include `x`).

``` r
library(dplyr)
library(dbplyr)

mf <- memdb_frame(g = c(1:3), x = 3:1, y = 3:1 + 3)
mf
#> # Source:   table<dbplyr_001> [?? x 3]
#> # Database: sqlite 3.37.0 [:memory:]
#>       g     x     y
#>   <int> <int> <dbl>
#> 1     1     3     6
#> 2     2     2     5
#> 3     3     1     4
mf %>% colnames()
#> [1] "g" "x" "y"
mf %>% select(-x) %>% colnames()
#> [1] "g" "y"
```

But when I load `connectapi`, `colnames()` grabs the colnames from the wrong place (from the `x` of the select operation object), and gives an incorrect answer.

```r
library(connectapi)
#> Registered S3 methods overwritten by 'connectapi':
#>   method            from  
#>   dim.tbl_lazy      dbplyr
#>   dimnames.tbl_lazy dbplyr
mf %>% colnames()
#> [1] "g" "x" "y"
mf %>% select(-x) %>% colnames()
#> [1] "g" "x" "y"
```

Similarly, joining is weird:

``` r
library(dplyr)
library(dbplyr)

mf1 <- memdb_frame(g = c(1:3), x = 3:1)
mf2 <- memdb_frame(g = c(1:3), y = 3:1 + 3)

left_join(mf1, mf2)
#> Joining, by = "g"
#> # Source:   lazy query [?? x 3]
#> # Database: sqlite 3.37.0 [:memory:]
#>       g     x     y
#>   <int> <int> <dbl>
#> 1     1     3     6
#> 2     2     2     5
#> 3     3     1     4

library(connectapi)
#> Registered S3 methods overwritten by 'connectapi':
#>   method            from  
#>   dim.tbl_lazy      dbplyr
#>   dimnames.tbl_lazy dbplyr
left_join(mf1, mf2)
#> Joining, by = "g"
#> Error in UseMethod("op_vars"): no applicable method for 'op_vars' applied to an object of class "c('op_join', 'op_double', 'op')"
```

I think both cases trace back to the `op_vars` methods in connectapi, and from [looking at dplyr's source](https://github.com/tidyverse/dbplyr/blob/70f408517a20514aa68c87d356e2c7f272d8f562/R/tbl-lazy.R#L108), I'm not sure if the overlapping methods are even necessary anymore.

**Comment by gadenbuie** [comment]
Here's a fun wrinkle! This issue was extra confusing to me because I wasn't using connectapi at the time. But it turns out that I had a script open in my workspace which _does use_ connectapi. In a fresh R session with only dbplyr loaded, if I change focus in the editor (in RStudio of course) to the script where connectapi is used, I instantly get:

```
Registered S3 methods overwritten by 'connectapi':
  method            from  
  dim.tbl_lazy      dbplyr
  dimnames.tbl_lazy dbplyr
```

**Comment by colearendt** [comment]
Oh noez!! We copied too directly rom the `dbplyr` prototype 🙈 Thanks for reporting!!

**Comment by fh-mthomson** [comment]
Chiming in that this issue sent us deep down the stack of `dbplyr` for several hours, only to realize it was a simple namespace issue in `connectapi`. 

@colearendt @aronatkins would it be reasonable to prioritize resolving these conflicts in the next release of `connectapi`? 

In the meantime, we can mitigate by ordering our library calls to prefer `dbplyr`, but feels goofy since users rarely load `dbplyr` directly (instead of indirectly via `library(dplyr)`).

```
library(connectapi)
library(dbplyr) # new call
library(dplyr)
```

cc: @fh-kpikhart
