### ISSUE TITLE
connectapi has been archived on CRAN

### ISSUE THREAD

**Issue by boshek** [rstudio/connectapi#180]
Apologies if you knew this already: https://cran.r-project.org/web/packages/connectapi/index.html

Are there any plans to re-submit or should we shift pipelines to use GitHub instead?

**Comment by colearendt** [comment]
Ugh. Yes, there are definitely plans to resubmit 😑 I missed the single warning that was sent 12/22. Working on it - apologies for the trouble!

**Comment by boshek** [comment]
Oh no apologies needed! One warning on December 22nd hardly seems sufficient notice to archive.

**Comment by biamorton** [comment]
Any updates on this?

**Comment by colearendt** [comment]
Oh yes! Merging the PR will close this 😄 Just gotta finish things off haha.
