### ISSUE TITLE
Development flow clean ups?

### ISSUE THREAD

**Issue by jonkeane** [rstudio/connectapi#214]
I'm taking some time to try and do some clean up chores here (clean lint errors, see if we can reduce the heav(ier) dependencies, that kind of thing). I've tried following the top ofhttps://github.com/rstudio/connectapi/blob/main/.github/CONTRIBUTING.md to get tests (and especially integration tests, since that is touching the code I'm looking at) running. 

In that process, I've noticed that the version of connect + connect image + R needed bumping. I'm happy to send a PR with those updates to the Makefile and docker-compose files but it also had me wondering if I'm missing a better way that folks are running these?

**Comment by colearendt** [comment]
I think you're on the right track. Unfortunately ever since I moved to an M1 mac, I have not been able to make much use of the integration tests locally 😅 So things have definitely fallen into disrepair.

**Comment by nealrichardson** [comment]
(Probably a separate issue) but we should add some tests with mock API responses so we can get test coverage without having to run integration tests against a live connect server.

**Comment by nealrichardson** [comment]
#223
