### ISSUE TITLE
Trying to create groups but search is returning two simular group names

### ISSUE THREAD

**Issue by anders-wiggers** [rstudio/connectapi#216]
We have encountered a problem while using the `groups_create_remote` method in the ConnectAPI R package to create groups. The issue arises when the method detects two groups with similar prefixes, where one group's name is the prefix of the other. Due to this, we are unable to create the groups using the provided API.

For example, consider the made-up group names `ABE` and `ABE-TEST`. When we create the group using the groups_create_remote method for `ABE` the method fails as `ABE` is also the prefix of the `ABE-TEST` group.

Previously, the same problem have been flagged in the `users_create_remote` method which have been solved in: https://github.com/rstudio/connectapi/issues/135

Thanks

**Comment by aronatkins** [comment]
@colearendt - It appears that your modifications to `users_create_remote` was not extended to `groups_create_remote`. Are they able to be directly ported over?

**Comment by colearendt** [comment]
Ahh interesting! Yeah, that does look like the same problem. I would definitely expect that fix to be transferable.

**Comment by aronatkins** [comment]
This issue is also internal support ticket 101966.

**Comment by anders-wiggers** [comment]
Hey, are there any updates on this issue?

**Comment by nealrichardson** [comment]
None yet, but we're planning some work in this package over the next month or two, and this will be on the list.

**Comment by toph-allen** [comment]
@anders-wiggers The change to support this has merged into the dev version, which you can test with `remotes::install_github("rstudio/connectapi")`. It'll be in our next release.
