### ISSUE TITLE
`get_usage_static` is misleading in name. Adapt to be relevant for all content.

### ISSUE THREAD

**Issue by kmasiello** [rstudio/connectapi#218]
The nomenclature of `get_usage_static` is not correct.  The Connect API documentation has been updated to better clarify that the non-Shiny endpoint `/v1/instrumentation/content/visits` is for:
> This endpoint returns a portion of the visit (or "hits") information for all content types other than Shiny applications. 

This is more than just static Rmd, Jupyter, etc. content, but includes the instrumentation information for non-Shiny web apps and APIs.  

A more inclusive approach would be to adapt this endpoint to combine the instrumentation data from the Shiny endpoint and the non-Shiny endpoint such that there was a general `get_content_usage()` function that returned basic data for every piece of content, and then a more detailed endpoint specific to shiny with the added session duration information, etc. A user should not have to think about what flavor their content is in order to query the correct endpoint for instrumentation data.

**Comment by toph-allen** [comment]
Closing in favor of #252
