### ISSUE TITLE
Is it possible to deploy a .qmd file to Posit Connect that uses {connectapi} functionality?

### ISSUE THREAD

**Issue by JT-39** [rstudio/connectapi#226]
Hi,

I am trying to use the `{connectapi}` package to set the schedule of a .qmd file on Posit Connect.

So the .qmd file runs and does what it does, then at the end of the script I have this bit of code:

```
client <- connectapi::connect(
  server = Sys.getenv("CONNECT_SERVER"),
  api_key = Sys.getenv("CONNECT_API_KEY"))

file_qmd <- connectapi::content_item(client, 
                                              app-guid)

file_qmd _variant <- connectapi::get_variant_default(file_qmd)
file_qmd _sched <- connectapi::get_variant_schedule(file_qmd _variant)
connectapi::set_schedule_dayofmonth(file_qmd _sched,
                                    n = 1,
                                    start_time = sched_time,
                                    day = sched_day,
                                    activate = TRUE,
                                    email = TRUE)
```

The code runs and works as expected on my local machine/ RStudio. The `{connectapi}` package updates the scheduling of the app on Posit Connect.
I want to deploy this to Posit Connect so that each time it runs it self-updates to the next schedule date.

However, I am coming across this error while deploying:

```
Quitting from lines 344-374 [unnamed-chunk-14] (file_push.qmd)
Error in `curl::curl_fetch_memory()`:
! Peer certificate cannot be authenticated with given CA certificates: [rsconnect-pp] Peer's Certificate issuer is not recognized.
Backtrace:
 1. connectapi::connect(server = Sys.getenv("CONNECT_SERVER"), api_key = Sys.getenv("CONNECT_API_KEY"))
 2. base::tryCatch(...)
 3. base (local) tryCatchList(expr, classes, parentenv, handlers)
 4. base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5. value[[3L]](cond)
Execution halted
Stopped session pings to http://127.0.0.1:37240
Unable to render the deployed content: Rendering exited abnormally: exit status 1
```

Is what I am trying to do possible/ easy? Do I need to include some other files (maybe SSL certificates, etc.?).

**Comment by nealrichardson** [comment]
What you're describing sounds similar to this issue, which also involves one app/document on Connect trying to access another item on Connect: https://docs.posit.co/troubleshooting/ssl/#scenario-4-troubleshooting-ssl-issues-with-pins-package

Do you remember setting up something with certificates on your local machine at some point?

That post offers a workaround you can add to your document, which may work for you. A better solution, if I understand correctly, would be to have your Connect server configured with whatever certificates you need to access it from your machine. Even though your qmd is already on the Connect server, it needs to communicate with the Connect API through the "front door", just as if it were running on a different machine. 

These docs may be helpful for getting the server config set:

* https://support.posit.co/hc/en-us/articles/115006524187-Publishing-to-a-Posit-formerly-RStudio-Connect-Server-with-a-Self-Signed-or-Untrusted-SSL-Certificate
* https://docs.posit.co/connect/admin/getting-started/local-install/initial-configuration/ssl-certificates/

**Comment by JT-39** [comment]
Thanks for responding @nealrichardson.

That's an interesting solution. I am not the dev person to ask about certificates unfortunately... but we think the error is because we are calling the API from the same server and it can't recognise the cert chain.

I am unsure about the workaround due to potential security concerns?

The certificates configuration is also a good idea. The only issue is I am not sure how I would produce these or even where to start. I have tried and been through those two links but am struggling to find where the certificates actually live.

Thanks for your ongoing help :)

**Comment by JT-39** [comment]
A colleague figured out the issue:

"I had to add the intermediate certificates to the trust store. Because it's calling the API from within the same server for some reason they are not being sent correctly so you get the certificate issuer error."

Hope this helps people.
