### ISSUE TITLE
Fix (or remove?) html tidy job

### ISSUE THREAD

**Issue by nealrichardson** [rstudio/connectapi#233]
```
❯ checking HTML version of manual ... NOTE
  Found the following HTML validation problems:
  tags.html:119:1 (tags.Rd:70): Warning: trimming empty <li>
```

**Comment by aronatkins** [comment]
This will probably require doc updates; it's complaining about the list-like thing here, and there's at least one empty item (search a tag tree):

https://github.com/rstudio/connectapi/blob/93d203195f8fa215bfcc1f3ff5b877d27d7d1c1e/R/tags.R#L28-L48

**Comment by nealrichardson** [comment]
Ah good catch, I looked but didn't spot it right off. That's an easy enough fix.

**Comment by aronatkins** [comment]
I only looked because I was worried that we had another round of htmltidy / roxygen nonsense to go through. Not so much, this time.
