### ISSUE TITLE
Add search to pkgdown for Connect API

### ISSUE THREAD

**Issue by fh-mthomson** [rstudio/connectapi#275]
While trying to interact with the Connect API, I often reference:
1. `connectapi` pkgdown: https://pkgs.rstudio.com/connectapi/
2. Connect app docs: https://docs.posit.co/connect/cookbook/

Two requests to make this slightly easier to find the relevant information:
1. Add Search functionality to the `connectapi` pkgdown site
2. Add Filter to Connect docs to limit search results to ONLY the API Cookbook and/or API Reference.

Motivating example: If I want to search for a specific endpoint name, I don't always want to see user-facing docs.

Thanks for the consideration!

**Comment by toph-allen** [comment]
I definitely agree that adding a filter to the Connect docs to limit only to the cookbook/API ref would be useful. I'm not sure how easy that would be, but I'll add a feature request to that effect in our issues for Connect.

**Comment by toph-allen** [comment]
As search was added by your pkgdown update PR, I'm closing this tracking issue. Thanks!
