### ISSUE TITLE
`get_audit_logs` breaks time

### ISSUE THREAD

**Issue by minemR** [rstudio/connectapi#290]
It seems that date time format has changed for audit logs and now time column is empty aka `NA`

problematic line:
https://github.com/rstudio/connectapi/blob/f053cff40b55dc46584a141d5458bef7e72cc52f/R/parse.R#L111

example:
```r
as.POSIXct(strptime('2023-08-22T14:13:14+03:00', format = "%Y-%m-%dT%H:%M:%SZ"))
```

**Comment by minemR** [comment]
#270

**Comment by toph-allen** [comment]
@minemR What version of Connect are you running? The format parses as expected when I check against the latest version.

**Comment by toph-allen** [comment]
@minemR What version of Connect are you using?

**Comment by minemR** [comment]
Posit Connect 2024.08.0

**Comment by aronatkins** [comment]
@minemR - Do you happen to know the if the server running Connect is configured to use a specific locale timezone or does it use UTC? We are pursuing a theory that Connect timestamps have a different format depending on the timezone of the server.

**Comment by minemR** [comment]
running `locale` gives:
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME=C.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
does this answer your question?

**Comment by aronatkins** [comment]
@minemR - what does `date` show on the Connect server?

**Comment by minemR** [comment]
`Thu Aug 29 08:55:02 EEST 2024`
