### ISSUE TITLE
Investigate error with pagination

### ISSUE THREAD

**Issue by toph-allen** [rstudio/connectapi#319]
- The error is mentioned in a comment in `groups_create_remote()`.

When the page size and number of results would require multiple pages, we instead see repeat pages. Is this a Connect error or a `connectapi` bug?

```r
> get_groups(client, page_size = 2, prefix = "c", limit = 10)
# A tibble: 10 × 3
   guid                                 name                 owner_guid                          
   <chr>                                <chr>                <chr>                               
 1 a6fb7cea- connect_dev          1a775703-
 2 68bad75b- cool_kids_of_the_dmv 1270410b-
 3 a6fb5cea- connect_dev          1a7a5703-
 4 68bad75b- cool_kids_of_the_dmv 1270410b-
 5 a6fb5cea- connect_dev          1a7a5703-
 6 68bad75b- cool_kids_of_the_dmv 1270410b-
 7 a6fb5cea- connect_dev          1a7a5703-
 8 68bad75b- cool_kids_of_the_dmv 1270410b-
 9 a6fb5cea- connect_dev          1a7a5703-
10 68bad75b- cool_kids_of_the_dmv 1270410b-
```

Originally committed here: https://github.com/rstudio/connectapi/commit/bec0b44e3f3513fa85edcf31d3bda0fbb27d23c2

**Comment by jonkeane** [comment]
This might be related to / fall out from https://github.com/rstudio/connect/issues/27060

**Comment by toph-allen** [comment]
@jonkeane I'm still going to investigate further — this is in a different API (groups vs group members) so may be a different bug.
