### ISSUE TITLE
`poll_task` is trowing a 404 error because of changes in api reference

### ISSUE THREAD

**Issue by francoisluc** [rstudio/connectapi#338]
I used the documented example in [posit documentation](https://docs.posit.co/connect/cookbook/content/rendering-content/) and got a 404 error. 
![Image](https://github.com/user-attachments/assets/af8befa8-35f2-42a0-887a-2c0afbdbb19b)

```r
library(connectapi)

CONTENT_GUID <- "34e425fb-179c-48e8-81bd-b334eb449f55"

client <- connect()
content <- content_item(client, CONTENT_GUID)
render_task <- content_render(content)

poll_task(render_task)
```
If you change this line
https://github.com/rstudio/connectapi/blame/f6093432582e1bed9ebcadbf613944cd691e5ead/R/deploy.R#L583

to
```r
  task_data <- con$task(task$task$id, wait = wait, first = first)
```

It solves the problem. I saw some changes to the tasks endpoint in august and I think this code was not updated as id parameter is now mandatory.

Thanks in advance for fixing this small bug !

**Comment by toph-allen** [comment]
@francoisluc Thanks for bringing this to our attention!

**Comment by toph-allen** [comment]
@francoisluc This is fixed in the dev version and will be in the next release.

**Comment by francoisluc** [comment]
@toph-allen Thanks for the quick fix, this is awesome.
