### ISSUE TITLE
Benchmarking get_content

### ISSUE THREAD

**Issue by tbradley1013** [rstudio/connectapi#52]
I am reposting this here from [`connectAnalytics`](https://github.com/tbradley1013/connectAnalytics/issues/12) as I think it is relevant here too. Can you all run this benchmark on your Connect Server? I believe @colearendt said it has 90+ pages of content when the page size is left at the default 25. I am curious if increasing the page size provides that large of a server with a significant speedup:

```
tmp <- connectapi::connect(host = Sys.getenv("CONNECT_SERVER"), api_key = Sys.getenv("CONNECT_API_KEY"))

microbenchmark::microbenchmark(
  w_page_size = connectapi::get_content(tmp, limit = Inf, page_size = 1e4), 
  wo_page_size = connectapi::get_content(tmp, limit = Inf)
)
#> Unit: milliseconds
#>          expr      min       lq     mean   median       uq      max neval
#>   w_page_size 276.8448 289.3661 301.1540 297.2429 304.8684 481.6506   100
#>  wo_page_size 510.5587 534.9695 552.8163 546.6944 562.0564 756.6520   100
```

If it does, it may be worth increasing the default page size on these queries in `get_content`. 

In addition, another suggested way of speeding up the `connectAnalytics` was to only retrieve data from content with usage data via the content GUID that is obtained from `get_usage_shiny` or `get_usage_static`. Is there any documentation that details how you can use the filter argument in the `get_apps` R6 method to filter by GUID? Right now, the only one that is clear is that you can filter by name:

```
get_content(tmp, filter = list(name = "my_app"))
```

I have tried numerous attempts at what the GUID filter name could be but have been unsuccessful so far. 

Thanks!

**Comment by colearendt** [comment]
Thanks @tbradley1013 ! Apologies for the delay in getting back to you! I've been slammed the past few weeks, but hopefully getting back around to some of the `connect-usage` stuff 😄

**Comment by tbradley1013** [comment]
No worries. Only pinging again because I was hoping to submit the application to the Shiny Contest to give it some exposure but I can't without an example app (and preferably one that loads in a reasonable amount of time!). If it doesn't get done before the deadline, it is no big deal, but thought it was worth mentioning!

**Comment by colearendt** [comment]
Awesome!! Exciting that you're entering the contest! I'll see if I can't take a look in the next few days - definitely want to enable the contest submission!
