### ISSUE TITLE
Add an integration test for "deployed deployer"

### ISSUE THREAD

**Issue by colearendt** [rstudio/connectapi#66]
Inspired by #65 and weird temp directory shenanigans, we should test that `connectapi` can be deployed to Connect and used inside of Connect's sandboxing.

This presents a bit of a "chicken and egg" problem because we will need the SHA that we are building so we can `remotes::install_github()` it and build the manifest... yuck

**Comment by toph-allen** [comment]
Removing this as part of issue cleanup. It would be good to have a piece of test content that uses `connectapi`, but our future work will almost certainly include the creation and deployment of these kinds of content.
