### ISSUE TITLE
Idea - Add get_content_tag

### ISSUE THREAD

**Issue by oude-gao** [rstudio/connectapi#67]
Hi, heavy user of RStudio Connect here, have queried the API myself previously and am really glad to find out about the `get_()` functions. I wonder if it's possible to add tags as one additional dimension alongside the content? If the tags are available somewhere on the server, I guess the schema name could be the dimension, and value is what has been selected as the tag.

**Comment by colearendt** [comment]
@oude-gao glad to hear, thank you!! I'm not sure if this is precisely what you are looking for (it is aimed less at "data" and more at "functionality"), but `get_content_tags()` just landed on `master` earlier today!

There is an article showing its use in context here: https://rstudio.github.io/connectapi/articles/articles/connectapi_tags.html

Do you mind describing the use case you're shooting for here? It always helps us to understand what our users are trying to accomplish on Connect as we formalize and improve the APIs that are available!!

**Comment by oude-gao** [comment]
Thanks! I will definitely check it out some time this week. I have actually tried to directly access the R6 object to get tags for individual content. It looks very promising.

What we are trying to achieve here is managing all the contents through tags in areas like setting security levels (group 1 only has access to tag 1, group 2 can access tag 1 and 2), content navigation (group 1 given a URL with the tag id to go to all content under tag 1), and content archiving. 

So far we are able to do all of them, by retrieving tag id for each content is still a little bit cumbersome, and I haven't had the time to organize the data in a more systematic way. At the end, we are envisioning a landing page for our audience, and links on the landing page will be arranged by tags where URLs with the tag ids are also embedded.

**Comment by colearendt** [comment]
That's really interesting! Thanks so much for sharing that use case! I have to admit I do not completely understand your workflow yet (and will try to think through this more deeply), but I did want to be sure I shared a few things

```
# an example and somewhat defunct (but not very pretty) pattern of creating a landing page
connectapi::tag_page()

# unexported because it is experimental
connectapi:::tag_page_iframe()
```

One of the things that may be less than ideal for the current implementation of `get_content_tags()` is that it does not provide a "get the ids assigned to this app." The raw R6 endpoint might do this (on the `Content` object itself), but I will keep this issue open so we can take a look at whether there is an easier way to provide that!

**Comment by oude-gao** [comment]
Thanks. This is really helpful.

I wish I had something more concrete to show you, but I'll get back to this once I sort my thoughts out. This package in general is the lifesaver of heavy RStudio Connect users indeed!

**Comment by colearendt** [comment]
Woops - I think this totally fell off my radar. However, wanted to share that there are a whole bunch more tag-specific functions that might interest you!

https://rstudio.github.io/connectapi/articles/articles/connectapi_tags.html

**Comment by oude-gao** [comment]
This is awesome. Exactly what i was looking for. Thanks for sharing!
