### ISSUE TITLE
Getting error when I try to create a remote user 

### ISSUE THREAD

**Issue by sclewis23** [rstudio/connectapi#79]
I'm getting strange error:
`connectapi::users_create_remote(connect = client, prefix = "yan.lu", expect = 1, check = TRUE)
Error: Can't convert `x` <logical> to match type of `to` <datetime<local>>.
Run `rlang::last_error()` to see where the error occurred.
`

If I change the check to FALSE it allow it to run.

**Comment by colearendt** [comment]
Interesting! Thanks for sharing this here! Do you mind sharing a bit more about your execution environment? 

For instance, can you share the output of:
```
Sys.getlocale()
Sys.timezone()
```

**Comment by sclewis23** [comment]
`> Sys.getlocale()
[1] "LC_CTYPE=en_US.UTF-8;LC_NUMERIC=C;LC_TIME=en_US.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=en_US.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=en_US.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=en_US.UTF-8;LC_IDENTIFICATION=C"
> Sys.timezone()
[1] "America/Los_Angeles"`

**Comment by sclewis23** [comment]
Ok, just noticed, I'm setting timezone to UTC, Sys.setenv(TZ = "UTC")....after disabling this the function works.
Any ideas why?
`
> Sys.getlocale()
[1] "LC_CTYPE=en_US.UTF-8;LC_NUMERIC=C;LC_TIME=en_US.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=en_US.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=en_US.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=en_US.UTF-8;LC_IDENTIFICATION=C"
> Sys.timezone()
[1] "UTC"
`

**Comment by sclewis23** [comment]
OK i'm still trying to get this to work in a rmarkdown, but I'm getting some error....so
I'm getting the User added, but when the function tries to return the get_users(client, prefix = "shannon.lewis"),
it isn't able to return the user, it seems to only return users if they have been given access to an app already.
`
> connectapi::get_users(client, page_size = 500, limit = Inf) %>% dplyr::filter(username == "zhirong.shen")
 A tibble: 1 x 11
  email                    username     first_name last_name user_role created_time        updated_time        active_time         confirmed locked guid                                
  <chr>                    <chr>        <chr>      <chr>     <chr>     <dttm>              <dttm>              <dttm>              <lgl>     <lgl>  <chr>                               
1 zhirong.shen@beigene.com zhirong.shen Zhirong    Shen      viewer    2020-12-07 22:33:19 2020-12-07 22:33:19 NA                  TRUE      FALSE  27bbb6c0-0bd4-4a56-a782-1ab603f7b642

> connectapi::get_users(client, prefix = "zhirong.shen", page_size = 500, limit = Inf)
Error: Can't convert `x` <logical> to match type of `to` <datetime<local>>.
Run `rlang::last_error()` to see where the error occurred.
`

**Comment by colearendt** [comment]
Ah yes. Apologies for the issue here - we are running into `vctrs` "very rigorous type safety." `active_time` is `NULL` when the user is first created, which is having a hard time being converted to `datetime` (which the `active_time` field requires).
