### ISSUE TITLE
retrieving log of deployment by GUID

### ISSUE THREAD

**Issue by yonicd** [rstudio/connectapi#80]
Is there a way to retrieve the std[err|out] of a session by GUID and commit hash? 

The RSC GUI shows that all the information is being stored on the server, it would be very useful for interrogating failing apps/rmd docs and if needed sharing them with RS support when things go really bad :)

**Comment by yonicd** [comment]
I found how to do this, but it would be a nice feature to add to the R6

```r

library(connectapi)
library(purrr)
 
client <- connect(
  host = keyring::key_get('RSC_SERVER'),
  api_key = keyring::key_get('RSC_APIKEY')
)

some_content <- get_content(client)

GUID <- some_content$guid[grepl('Retention',some_content$title)]

rsc_logs <- GET(file.path(rsc_stem,glue::glue("applications/{GUID}/jobs")),
                add_headers(Authorization = paste("Key",keyring::key_get('RSC_APIKEY') )))

rsc_logs_content <- content(rsc_logs)

rsc_logs_keys <- purrr::map(rsc_logs_content,~.x$key)

rsc_log_objs <- purrr::map(rsc_logs_keys,function(x,guid){
  GET(file.path(rsc_stem,glue::glue("applications/{GUID}/job/{x}")),
      add_headers(Authorization = paste("Key",keyring::key_get('RSC_APIKEY') )))
},guid = GUID)


rsc_log_objs_content <- lapply(rsc_log_objs,content)

rsc_log_objs_content_errs <- purrr::map(rsc_log_objs_content, ~.x$logged_error)
rsc_log_objs_content_errs <- purrr::discard(rsc_log_objs_content_errs,is.null)

```

**Comment by colearendt** [comment]
Great detective work! I am going to work on improving the docs here, as functions to do what you want are in the package. However, it seems changes to the API or vctrs have made things strict enough to fail. Once fixed, you can expect something like:

(using my monkeypatched version)

``` r
library(connectapi)
con <- connect()
#> Defining Connect with host: https://colorado.rstudio.com/rsc

myrmd <- content_item(con, "1fd4d6e3-4cb4-4579-9339-9b990b6bd89e")

get_variants(myrmd)
#> Warning: The `get_variants` function is experimental and subject to change without warning in a future release
#> This warning is displayed once per session.
#> # A tibble: 8 x 14
#>      id app_id key   bundle_id is_default name  email_collabora… email_viewers
#>   <int>  <int> <chr>     <int> <lgl>      <chr> <lgl>            <lgl>        
#> 1  1635   1070 wtA6…     26128 FALSE      rand… FALSE            FALSE        
#> 2  3349   1070 H4BV…     26128 FALSE      cole… FALSE            FALSE        
#> 3  3289   1070 d972…     26128 FALSE      SGD   FALSE            FALSE        
#> 4  1859   1070 zXxt…     26128 FALSE      my-s… FALSE            FALSE        
#> 5  1521   1070 UmYM…      5915 FALSE      my-r… FALSE            FALSE        
#> 6  1388   1070 AbnF…      5915 FALSE      rand… FALSE            FALSE        
#> 7  1200   1070 W5NC…      5915 FALSE      EUR   FALSE            FALSE        
#> 8  1153   1070 CnFQ…     26128 TRUE       defa… FALSE            FALSE        
#> # … with 6 more variables: created_time <dttm>, rendering_id <int>,
#> #   render_time <dttm>, render_duration <dbl>, visibility <chr>, owner_id <int>

one_variant <- get_variant_default(myrmd)
#> Warning: The `get_variant_default` function is experimental and subject to change without warning in a future release
#> This warning is displayed once per session.

# or by key
# get_variant(myrmd, "key")

get_jobs(one_variant)
#> Warning: The `get_jobs` function is experimental and subject to change without warning in a future release
#> This warning is displayed once per session.
#> # A tibble: 38 x 14
#>        id   pid key   app_id app_guid variant_id bundle_id start_time         
#>     <int> <int> <chr>  <int> <chr>         <int>     <int> <dttm>             
#>  1 5.58e6 18488 zPeW…   1070 1fd4d6e…       1174     26128 2020-11-15 15:13:23
#>  2 5.48e6 14869 PKN5…   1070 1fd4d6e…       1174     26128 2020-11-11 15:13:11
#>  3 5.45e6 22914 DrYn…   1070 1fd4d6e…       1153     26128 2020-11-10 11:00:05
#>  4 5.85e6 19381 xcaQ…   1070 1fd4d6e…       1174     26128 2020-11-26 15:12:56
#>  5 5.80e6  9151 E74L…   1070 1fd4d6e…       1174     26128 2020-11-24 15:13:05
#>  6 5.70e6 23223 MeWZ…   1070 1fd4d6e…       1174     26128 2020-11-20 15:13:05
#>  7 5.75e6  2867 vWur…   1070 1fd4d6e…       1174     26128 2020-11-22 15:13:16
#>  8 5.88e6 10969 tep1…   1070 1fd4d6e…       1174     26128 2020-11-27 15:13:06
#>  9 5.62e6 22481 msOW…   1070 1fd4d6e…       1153     26128 2020-11-17 11:00:25
#> 10 5.65e6  3253 r2JY…   1070 1fd4d6e…       1635     26128 2020-11-18 14:41:55
#> # … with 28 more rows, and 6 more variables: end_time <dttm>, tag <chr>,
#> #   exit_code <int>, finalized <lgl>, hostname <chr>, variant_key <chr>

get_job(one_variant, get_jobs(one_variant)[1, "key"])
#> Warning: The `get_job` function is experimental and subject to change without warning in a future release
#> This warning is displayed once per session.
#> # A tibble: 1 x 17
#>     pid key   app_id variant_id bundle_id tag   finalized hostname origin stdout
#>   <int> <chr>  <int>      <int>     <int> <chr> <lgl>     <chr>    <chr>  <list>
#> 1 18488 zPeW…   1070       1174     26128 buil… TRUE      connect2 0001-… <chr …
#> # … with 7 more variables: stderr <list>, logged_error <list>,
#> #   start_time <dttm>, end_time <dttm>, exit_code <int>, app_guid <chr>,
#> #   variant_key <chr>
```

<sup>Created on 2020-12-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Feedback on this workflow or what could be improved are always welcome!!

**Comment by yonicd** [comment]
That looks nice! Thanks for the explanation. Can’t wait for the patch, it will definitely make working w connect much smoother.

**Comment by yonicd** [comment]
After a successful deployment how to i query the stdout/err of an instance of an app? if i use the pipeline you have above it will return the same number of rows regardless if i refresh the page (create a new RSession) unless I am misunderstanding how the apps are being run.

Are the PID per build/deployment or per app initialization within a given build?

Also are there docs describing the columns returned for `get_job()`?

thanks!

```r
library(connectapi)

client <- connect(
  host = keyring::key_get('RSC_SERVER'),
  api_key = keyring::key_get('RSC_APIKEY')
)

GUID <- get_content(client)%>%
  dplyr::filter(grepl('MYAPP',title))%>%
  dplyr::pull(guid)

keys <- client%>%
  content_item(GUID)%>%
  get_variant_default()%>%
  get_jobs()%>%
  dplyr::pull(key)

jobs <- purrr::map_df(keys,function(x){
  client%>%
    content_item(GUID)%>%
    get_variant_default()%>%
    get_job(x)
})
```

**Comment by colearendt** [comment]
This is a great question, and unfortunately the documentation is currently very weak around jobs. That is something we are aiming to improve! Basically you can imagine that "jobs" is giving you what you see within the "logs" pane. Each entry corresponds to a PID / a linux process. A linux process for a Shiny app (for instance) sticks around and potentially serves many users, even concurrently (which can be tweaked in the "Runtime" pane / runtime settings).

If you change an environment variable, for instance, you will see the old PIDs get stopped, and a new one started.

**Comment by yonicd** [comment]
thanks for the explanation.

So is there a way to view a given session of the current build by user?

**Comment by colearendt** [comment]
Woops - missed this. So there are a couple of pieces here, and I think some of this will be product feedback:

- The mapping from user session to linux PID is not generally made available outside of the R process. However, the R process can figure out its PID (via a system command), and knows the user's session ID (as well as user's ID). So the mapping from user session to PID, while it does not exist in state anywhere, _could_ be defined and managed by you
- Logging in Shiny is ordered and usually does not distinguish between user sessions. This is something that you could probably change via an R package that creates your log messages, however, you will see _all_ logs for a given PID in the same log file
- In RStudio Connect, you can get log messages for a PID. It is worth noting that the PIDs are unique only at a given point in time and on a given host, so it is possible that there will be some non-uniqueness floating about over time.
- If you are talking about a "specific version of your source code," then you are looking for the "currently deployed bundle id," which is unfortunately not made available to the process (or in the log) that I am aware of. This is definitely something that needs to be improved! In most cases, you can get this from the API, however there are edge cases where the old bundle ID could be running for a bit longer after a new deployment

In general, I think this is a pretty hard mapping to get right today, and we would love to make it easier in the product! Do you mind articulating what problem you are trying to solve, and if you have any ideas how your ideal workflow would work, so that I can share them with the team? 😄

**Comment by yonicd** [comment]
happy to talk over zoom or slack if that is possible to better articulate the question.

**Comment by dpastoor** [comment]
You'd need to use a logging framework that allows you to provide structured logging. For example: https://github.com/metrumresearchgroup/logrrr and https://github.com/daroczig/logger

For example this is the scaffold entry point for our applications these days:

```
suppressPackageStartupMessages({
  library(shiny)
  library(logrrr)
  library(fs)
})

cfg <- config::get(file = "app-config.yml", use_parent = FALSE)

#### SETUP -----

whoami <- function(session) {
  if (!is.null(session$user)) {
    return(session$user)
  } 
  return("UNKNOWN")
}

if (cfg$is_production) {
  lgr <- Logrrr$new(log_level = "DEBUG",
                    output =  LogOutput$new())
} else {
  if (file_exists("debug-log.txt")) {
    file_delete("debug-log.txt") 
  }
  lgr <- Logrrr$new(log_level = "TRACE",
                    output = list(text = LogOutput$new(),
                                  file = LogOutput$new(format_func = JSONFormatter(), output = "debug-log.txt")))
}

lgr$with_fields(config = attributes(cfg)$config)$info("configuration")

ui <- fluidPage(
  h3(sprintf("app version: %s", cfg$version))
)

server <- function(input, output, session) {
  SESSION_ID <- as.character(floor(runif(1)*1e10))
  # make a copy of the global logger to tie to the specific user session
  # and have that also include fields about who they are and their session
  lgr <- lgr$clone()
  lgr$set_fields(user = whoami(session), session = SESSION_ID)
  lgr$with_fields(is_production = cfg$is_production)$info("starting new session")
  
  
}

shinyApp(ui, server)
```

The sessionid and username are then attached to every log message. Of course this does have the limitation of internal functionality that just prints/messages normally, eg messages coming out from other packages invoked in the app, that would not be filterable, so mileage will vary around what is being attempted to be extracted.

**Comment by yonicd** [comment]
that would have to be appended to every app on an RSC server?

**Comment by dpastoor** [comment]
something along those lines would yeah - like the fundamental issue is having multiple people in a given R session there is no way i could think of to easily sink stdout/err in a way that would differentiate. stdout/err is going to be collected per R process. Hence, you have to attach metadata at the log level to manage that.

Now one thing you could do, if you really need that granularity, and don't want to retrofit, is just straight change the rstudio connect config to only have 1 person per R session. You'll pay some memory penalties around a fresh R session per person, but you'd get that GUID and the separation of logs. 

The nice thing about providing those tags, is it is an entrypoint into "true" log aggregation and leveraging systems purpose-built to handle logs/search them/etc, set alerts around it:

We use loki now and its been great: https://grafana.com/blog/2020/05/12/an-only-slightly-technical-introduction-to-loki-the-prometheus-inspired-open-source-logging-system/

But you can keep it simpler.

The other benefit that such a framework provides, is in addition to patterns such as what you're exploring above, you could (either/instead) set with logrrr the ability to write logs out to a text file. You can also, on that system, have an rstudio connect cron job run every n minutes to read the logs and check if any of level warn/error and if so email admin. That way you don't have to have users necessarily even be the one to report errors and can get proactive alerts.
