### ISSUE TITLE
Package installation requires online connection

### ISSUE THREAD

**Issue by johanneswaage** [rstudio/connectapi#82]
Hi,
Installation requires the webshot from github. 
This is unfortunate, as we use this package in production, which is offline.
Can this package requirement be removed?
Regards,
J

**Comment by colearendt** [comment]
Hey @johanneswaage can you share the error you are getting on installation? So sorry for the trouble there - we can definitely remove that requirement. It is an old experiment that I am pretty sure nobody uses.

**Comment by johanneswaage** [comment]
@colearendt Thanks! I’m not at my console atm, but we’re simply getting a timeout from GitHub, since we have no connectivity. CRAN and internal packages are retrieved through RSPM
