### ISSUE TITLE
retrieving an img created by a deployment as a link

### ISSUE THREAD

**Issue by yonicd** [rstudio/connectapi#84]
I have a static Rmd that I am deploying and want to send on image saved to disk using fig.path in the knitr setup chunk. How can i send one of the images as a link to someone? Is there a way through the connectapi to get to those files?

**Comment by jlfsjunior** [comment]
One alternative is to [serve them with Plumber](https://www.rplumber.io/articles/routing-and-input.html#static-file-handler).

**Comment by yonicd** [comment]
I havent tried that out yet in RSC. Is there an example of creating connections to files inside the server?

**Comment by jlfsjunior** [comment]
> I havent tried that out yet in RSC. Is there an example of creating connections to files inside the server?

You can replace the `./files/static` directory (in the example) to any path on the server, provided that the RunAs user has access to it. 

Note: this is quite off-topic for this repo.

**Comment by yonicd** [comment]
apologies for the off topic

Is there a specific type of license needed to deploy plumber apis?

```
Preparing to deploy api...DONE
Uploading bundle for api: 20...DONE
Deploying bundle: 114 for api: 20 ...
Api deployment failed with error: API applications are not permitted by your license.
```

**Comment by yonicd** [comment]
figured out that is a base license wo plumber support.

**Comment by yonicd** [comment]
@cderv had the solution: https://docs.rstudio.com/connect/user/rmarkdown/#r-markdown-output-files

**Comment by cderv** [comment]
Always glad to help !
