### ISSUE TITLE
Update endpoints available to RStudio Connect 1.8.6

### ISSUE THREAD

**Issue by ian-flores** [rstudio/connectapi#94]
RStudio Connect 1.8.6 offers a new set of endpoints that are not all documented and/or included in the current version of the `connectapi` package. We can track the new endpoints and their documentation from here: https://docs.rstudio.com/connect/1.8.6/api/#overview

**Comment by colearendt** [comment]
Some ideas:
- [Content APIs / Env Vars](https://docs.rstudio.com/connect/api/#tag--Content)
- [Content ACLs - we may need to change our API](https://docs.rstudio.com/connect/api/#tag--Content-Permissions)
- [Tag stuff](https://docs.rstudio.com/connect/api/#tag--Tags)
- [Task endpoint](https://docs.rstudio.com/connect/api/#tag--Tasks)
- [Vanity URLs](#113)

**Comment by rstub** [comment]
It seems as manipulating the `run_as` user also uses the old API:
https://github.com/rstudio/connectapi/blob/e88deb55b47414467d2720c4c625cbbea6194732/R/content.R#L52-L64
